export PS1='\[\033[00;32m\]\u\[\033[00;32m\]@\[\033[00;32m\]\h\[\033[00;33m\]:\[\033[00;31m\]\w\[\033[00;32m\]$ \[\033[00m\]'

# PATHS
export PATH="/usr/local/sbin:/usr/sbin:/sbin:$PATH"

if [ -d /usr/local/go ]; then
  export PATH=$PATH:/usr/local/go/bin
fi

if [ -d ~/.rbenv ]; then
  export PATH="$HOME/.rbenv/bin:$PATH"
fi

# Aliases
alias ls="ls --color"

# Ruby
if [ -d ~/.rbenv ]; then
  eval "$(rbenv init -)"
fi
